#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Telescope

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Telescope.Apollo_Telescope_C
// 0x0000 (0x0BC8 - 0x0BC8)
class AApollo_Telescope_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Apollo_Telescope_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Apollo_Telescope_C")
	}
	static class AApollo_Telescope_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Telescope_C>();
	}
};
DUMPER7_ASSERTS_AApollo_Telescope_C;

}

