#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Artemis_Fence_WroughtIron_B

#include "Basic.hpp"

#include "Parent_BuildingWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Artemis_Fence_WroughtIron_B.Artemis_Fence_WroughtIron_B_C
// 0x0000 (0x0D48 - 0x0D48)
class AArtemis_Fence_WroughtIron_B_C final : public AParent_BuildingWall_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Artemis_Fence_WroughtIron_B_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Artemis_Fence_WroughtIron_B_C")
	}
	static class AArtemis_Fence_WroughtIron_B_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AArtemis_Fence_WroughtIron_B_C>();
	}
};
DUMPER7_ASSERTS_AArtemis_Fence_WroughtIron_B_C;

}

