#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaBroadcastPlayerEventScore

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Slate_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaBroadcastPlayerEventScore.AthenaBroadcastPlayerEventScore_C
// 0x0018 (0x0350 - 0x0338)
class UAthenaBroadcastPlayerEventScore_C final : public UAthenaBroadcastPlayerEventScoreWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UScaleBox*                              ScaleBox_0;                                        // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EStretch                                      OldStretch;                                        // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnPointTextSet();
	void ExecuteUbergraph_AthenaBroadcastPlayerEventScore(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaBroadcastPlayerEventScore_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaBroadcastPlayerEventScore_C")
	}
	static class UAthenaBroadcastPlayerEventScore_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaBroadcastPlayerEventScore_C>();
	}
};
DUMPER7_ASSERTS_UAthenaBroadcastPlayerEventScore_C;

}

