#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaInventoryItemTileButton_Currency

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "CommonInput_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaInventoryItemTileButton_Currency.AthenaInventoryItemTileButton_Currency_C
// 0x0020 (0x1520 - 0x1500)
class UAthenaInventoryItemTileButton_Currency_C final : public UAthenaInventoryItemTileButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1500(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_0;                                          // 0x1508(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonVisualAttachment*                InputActionWrapper;                                // 0x1510(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void UpdateInteractionWidgetVisibility();
	struct FEventReply OnMouseButtonDown_Border(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent);
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);
	bool OnDrop(const struct FGeometry& MyGeometry, const struct FPointerEvent& PointerEvent, class UDragDropOperation* Operation);
	void OnDragDetected(const struct FGeometry& MyGeometry, const struct FPointerEvent& PointerEvent, class UDragDropOperation** Operation);
	void HandleIntro();
	void ExecuteUbergraph_AthenaInventoryItemTileButton_Currency(int32 EntryPoint);
	void BP_OnUnhovered();
	void BP_OnHovered();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaInventoryItemTileButton_Currency_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaInventoryItemTileButton_Currency_C")
	}
	static class UAthenaInventoryItemTileButton_Currency_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaInventoryItemTileButton_Currency_C>();
	}
};
DUMPER7_ASSERTS_UAthenaInventoryItemTileButton_Currency_C;

}

