#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaChallengeListEntry_GoalCard

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonInput_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaChallengeListEntry_GoalCard.AthenaChallengeListEntry_GoalCard_C
// 0x0010 (0x0380 - 0x0370)
class UAthenaChallengeListEntry_GoalCard_C final : public UAthenaChallengeListEntry_GoalCard
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UGoalsPageQuestCard_C*                  JustAPreviewFeelFreeToRemoveMe;                    // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void IsUsingGamepad(bool* Return_Value);
	void ExecuteUbergraph_AthenaChallengeListEntry_GoalCard(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaChallengeListEntry_GoalCard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaChallengeListEntry_GoalCard_C")
	}
	static class UAthenaChallengeListEntry_GoalCard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaChallengeListEntry_GoalCard_C>();
	}
};
DUMPER7_ASSERTS_UAthenaChallengeListEntry_GoalCard_C;

}

