#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BBE_HideIfAugmentsOpen

#include "Basic.hpp"

#include "PlayerAugmentsUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BBE_HideIfAugmentsOpen.BBE_HideIfAugmentsOpen_C
// 0x0000 (0x0090 - 0x0090)
class UBBE_HideIfAugmentsOpen_C final : public UFortMobileActionBBE_AugmentShoot
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BBE_HideIfAugmentsOpen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BBE_HideIfAugmentsOpen_C")
	}
	static class UBBE_HideIfAugmentsOpen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBBE_HideIfAugmentsOpen_C>();
	}
};
DUMPER7_ASSERTS_UBBE_HideIfAugmentsOpen_C;

}

