#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Artemis_Hedge_Parent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Artemis_Hedge_Parent.BP_Artemis_Hedge_Parent_C
// 0x0010 (0x0BD8 - 0x0BC8)
class ABP_Artemis_Hedge_Parent_C : public ABuildingProp
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BC8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        SnowCoverageAmount;                                // 0x0BD0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_Artemis_Hedge_Parent(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Artemis_Hedge_Parent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Artemis_Hedge_Parent_C")
	}
	static class ABP_Artemis_Hedge_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Artemis_Hedge_Parent_C>();
	}
};
DUMPER7_ASSERTS_ABP_Artemis_Hedge_Parent_C;

}

