#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AthenaFullScreenMapPanel

#include "Basic.hpp"

#include "BP_AthenaFullScreenMapPanel_classes.hpp"
#include "BP_AthenaFullScreenMapPanel_parameters.hpp"


namespace SDK
{

// Function BP_AthenaFullScreenMapPanel.BP_AthenaFullScreenMapPanel_C.OnMapGameInfoWidgetCreated
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaFullScreenMapPanel_C::OnMapGameInfoWidgetCreated(class UUserWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaFullScreenMapPanel_C", "OnMapGameInfoWidgetCreated");

	Params::BP_AthenaFullScreenMapPanel_C_OnMapGameInfoWidgetCreated Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AthenaFullScreenMapPanel.BP_AthenaFullScreenMapPanel_C.ExecuteUbergraph_BP_AthenaFullScreenMapPanel
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaFullScreenMapPanel_C::ExecuteUbergraph_BP_AthenaFullScreenMapPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaFullScreenMapPanel_C", "ExecuteUbergraph_BP_AthenaFullScreenMapPanel");

	Params::BP_AthenaFullScreenMapPanel_C_ExecuteUbergraph_BP_AthenaFullScreenMapPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AthenaFullScreenMapPanel.BP_AthenaFullScreenMapPanel_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_AthenaFullScreenMapPanel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaFullScreenMapPanel_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AthenaFullScreenMapPanel.BP_AthenaFullScreenMapPanel_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UBP_AthenaFullScreenMapPanel_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaFullScreenMapPanel_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

