#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AthenaMapLegendsWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_AthenaMapLegendsWidget.BP_AthenaMapLegendsWidget_C
// 0x0010 (0x0430 - 0x0420)
class UBP_AthenaMapLegendsWidget_C final : public UAthenaMapLegendWidget
{
public:
	class USafeZone*                              SafeZone;                                          // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VBox_Content;                                      // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AthenaMapLegendsWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AthenaMapLegendsWidget_C")
	}
	static class UBP_AthenaMapLegendsWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AthenaMapLegendsWidget_C>();
	}
};
DUMPER7_ASSERTS_UBP_AthenaMapLegendsWidget_C;

}

