#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BroadcastPost

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BroadcastPost.BP_BroadcastPost_C
// 0x0020 (0x02B0 - 0x0290)
class ABP_BroadcastPost_C final : public AActor
{
public:
	class UPostProcessComponent*                  Extreme;                                           // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPostProcessComponent*                  PostProcess;                                       // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          ExtremePostEnabled;                                // 0x02A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BroadcastPost_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BroadcastPost_C")
	}
	static class ABP_BroadcastPost_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BroadcastPost_C>();
	}
};
DUMPER7_ASSERTS_ABP_BroadcastPost_C;

}

