#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Container_FruitBaskets_D

#include "Basic.hpp"

#include "Graybox_Prop_Small_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Container_FruitBaskets_D.BP_Container_FruitBaskets_D_C
// 0x0000 (0x0BD0 - 0x0BD0)
class ABP_Container_FruitBaskets_D_C final : public AGraybox_Prop_Small_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Container_FruitBaskets_D_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Container_FruitBaskets_D_C")
	}
	static class ABP_Container_FruitBaskets_D_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Container_FruitBaskets_D_C>();
	}
};
DUMPER7_ASSERTS_ABP_Container_FruitBaskets_D_C;

}

