#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lightsource_CH5_GlobalProp_PointLight

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"


namespace SDK::Params
{

// Function BP_Lightsource_CH5_GlobalProp_PointLight.BP_Lightsource_CH5_GlobalProp_PointLight_C.GetTimeOfDayBlueprintDefaultVariables
// 0x0020 (0x0020 - 0x0000)
struct BP_Lightsource_CH5_GlobalProp_PointLight_C_GetTimeOfDayBlueprintDefaultVariables final
{
public:
	struct FTimeOfDayBlueprintDefaultVariables    OutVariables;                                      // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
	struct FTimeOfDayBlueprintDefaultVariables    CallFunc_GetTimeOfDayBlueprintDefaultVariables_OutVariables; // 0x0010(0x0010)(NoDestructor)
};
DUMPER7_ASSERTS_BP_Lightsource_CH5_GlobalProp_PointLight_C_GetTimeOfDayBlueprintDefaultVariables;

}

