#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lightsource_CH5_GlobalProp_PointLight

#include "Basic.hpp"

#include "BP_Lightsource_CH5_GlobalProp_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Lightsource_CH5_GlobalProp_PointLight.BP_Lightsource_CH5_GlobalProp_PointLight_C
// 0x0008 (0x0BE0 - 0x0BD8)
class ABP_Lightsource_CH5_GlobalProp_PointLight_C : public ABP_Lightsource_CH5_GlobalProp_Parent_C
{
public:
	class UPointLightComponent*                   PointLight;                                        // 0x0BD8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void GetTimeOfDayBlueprintDefaultVariables(struct FTimeOfDayBlueprintDefaultVariables* OutVariables);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Lightsource_CH5_GlobalProp_PointLight_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Lightsource_CH5_GlobalProp_PointLight_C")
	}
	static class ABP_Lightsource_CH5_GlobalProp_PointLight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Lightsource_CH5_GlobalProp_PointLight_C>();
	}
};
DUMPER7_ASSERTS_ABP_Lightsource_CH5_GlobalProp_PointLight_C;

}

