#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lightsource_CH5_GlobalProp_Parent

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Lightsource_CH5_GlobalProp_Parent.BP_Lightsource_CH5_GlobalProp_Parent_C
// 0x0010 (0x0BD8 - 0x0BC8)
class ABP_Lightsource_CH5_GlobalProp_Parent_C : public ABuildingProp
{
public:
	class UTODLightingComponent_C*                TODLightingComponent;                              // 0x0BC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	EFortDayPhase                                 Test_Day_Phase;                                    // 0x0BD0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Disable_Static_Mesh_Shadow_Casting;                // 0x0BD1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void NewFunction();
	void GetTimeOfDayBlueprintDefaultVariables(struct FTimeOfDayBlueprintDefaultVariables* OutVariables);

	void CollectAssetReferencesToAllow(struct FFortExposedAssetReferenceCollector& Collector) const;
	void BuildExposedAssetProviderVersion(struct FFortExposedAssetProviderVersion& Version) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Lightsource_CH5_GlobalProp_Parent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Lightsource_CH5_GlobalProp_Parent_C")
	}
	static class ABP_Lightsource_CH5_GlobalProp_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Lightsource_CH5_GlobalProp_Parent_C>();
	}
};
DUMPER7_ASSERTS_ABP_Lightsource_CH5_GlobalProp_Parent_C;

}

