#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MilkshakeControllerComponent

#include "Basic.hpp"

#include "MilkshakeRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MilkshakeControllerComponent.BP_MilkshakeControllerComponent_C
// 0x0000 (0x0368 - 0x0368)
class UBP_MilkshakeControllerComponent_C final : public UMilkshakeControllerComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MilkshakeControllerComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MilkshakeControllerComponent_C")
	}
	static class UBP_MilkshakeControllerComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MilkshakeControllerComponent_C>();
	}
};
DUMPER7_ASSERTS_UBP_MilkshakeControllerComponent_C;

}

