#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Milkshake_EarthquakeDebug

#include "Basic.hpp"

#include "BP_Milkshake_EarthquakeDebug_classes.hpp"
#include "BP_Milkshake_EarthquakeDebug_parameters.hpp"


namespace SDK
{

// Function BP_Milkshake_EarthquakeDebug.BP_Milkshake_EarthquakeDebug_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Milkshake_EarthquakeDebug_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Milkshake_EarthquakeDebug_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Milkshake_EarthquakeDebug.BP_Milkshake_EarthquakeDebug_C.DestroyComponents
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UActorComponent*>&         Components                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void ABP_Milkshake_EarthquakeDebug_C::DestroyComponents(TArray<class UActorComponent*>& Components)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Milkshake_EarthquakeDebug_C", "DestroyComponents");

	Params::BP_Milkshake_EarthquakeDebug_C_DestroyComponents Parms{};

	Parms.Components = std::move(Components);

	UObject::ProcessEvent(Func, &Parms);

	Components = std::move(Parms.Components);
}

}

