#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Outdoor_PierPlanter_A_B

#include "Basic.hpp"

#include "BP_Planter_Parent_V2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Outdoor_PierPlanter_A_B.BP_Outdoor_PierPlanter_A_B_C
// 0x0000 (0x0C88 - 0x0C88)
class ABP_Outdoor_PierPlanter_A_B_C final : public ABP_Planter_Parent_V2_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Outdoor_PierPlanter_A_B_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Outdoor_PierPlanter_A_B_C")
	}
	static class ABP_Outdoor_PierPlanter_A_B_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Outdoor_PierPlanter_A_B_C>();
	}
};
DUMPER7_ASSERTS_ABP_Outdoor_PierPlanter_A_B_C;

}

