#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Outdoor_FountainLg_B_B

#include "Basic.hpp"

#include "Graybox_Prop_Large_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Outdoor_FountainLg_B_B.BP_Outdoor_FountainLg_B_B_C
// 0x0018 (0x0BE8 - 0x0BD0)
class ABP_Outdoor_FountainLg_B_B_C final : public AGraybox_Prop_Large_C
{
public:
	class UStaticMeshComponent*                   SM_Outdoor_FountainCenterWater_B;                  // 0x0BD0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Outdoor_FountainWaterLg_A;                      // 0x0BD8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Outdoor_FountainCenter_B;                       // 0x0BE0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Outdoor_FountainLg_B_B_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Outdoor_FountainLg_B_B_C")
	}
	static class ABP_Outdoor_FountainLg_B_B_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Outdoor_FountainLg_B_B_C>();
	}
};
DUMPER7_ASSERTS_ABP_Outdoor_FountainLg_B_B_C;

}

