#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerStateCustomFeedMessages

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlayerStateCustomFeedMessages.BP_PlayerStateCustomFeedMessages_C
// 0x0000 (0x0108 - 0x0108)
class UBP_PlayerStateCustomFeedMessages_C final : public UFortPlayerStateComponent_CustomFeedMessage
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerStateCustomFeedMessages_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerStateCustomFeedMessages_C")
	}
	static class UBP_PlayerStateCustomFeedMessages_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PlayerStateCustomFeedMessages_C>();
	}
};
DUMPER7_ASSERTS_UBP_PlayerStateCustomFeedMessages_C;

}

