#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_MeshGrassUtility

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_MeshGrassUtility.BPI_MeshGrassUtility_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_MeshGrassUtility_C final
{
public:
	void PostSpawn(const TArray<class UInstancedStaticMeshComponent*>& ISMs);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_MeshGrassUtility_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_MeshGrassUtility_C")
	}
	static class IBPI_MeshGrassUtility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_MeshGrassUtility_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_MeshGrassUtility_C;

}

