#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChaosBlueprintLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class ChaosBlueprintLibrary.ChaosBlueprintLibraryBPLibrary
// 0x0000 (0x0028 - 0x0028)
class UChaosBlueprintLibraryBPLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void ClothControllerWriteToSimulation(const class UCustomCharacterPartAnimInstance* CharacterPartAnimInstance, class FString& ClothingAssetName, struct FClothCoreSettings& ClothCoreSettings, struct FClothParameters& ClothSettings, struct FVector& WindVelocity, struct FClothParameters* OutWorldSpaceClothSettings, struct FVector* OutWorldSpaceWindVelocity);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ChaosBlueprintLibraryBPLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ChaosBlueprintLibraryBPLibrary")
	}
	static class UChaosBlueprintLibraryBPLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChaosBlueprintLibraryBPLibrary>();
	}
};
DUMPER7_ASSERTS_UChaosBlueprintLibraryBPLibrary;

}

