#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CRDPlayerTrackerUI

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class CRDPlayerTrackerUI.CRDPlayerTrackerUIComponent
// 0x0008 (0x00A8 - 0x00A0)
class UCRDPlayerTrackerUIComponent final : public UActorComponent
{
public:
	class UCRDPlayerTrackerWidget*                SpawnedWidget;                                     // 0x00A0(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CRDPlayerTrackerUIComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CRDPlayerTrackerUIComponent")
	}
	static class UCRDPlayerTrackerUIComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCRDPlayerTrackerUIComponent>();
	}
};
DUMPER7_ASSERTS_UCRDPlayerTrackerUIComponent;

// Class CRDPlayerTrackerUI.CRDPlayerTrackerWidget
// 0x0010 (0x0338 - 0x0328)
class UCRDPlayerTrackerWidget final : public UFortHUDElementWidget
{
public:
	uint8                                         Pad_328[0x10];                                     // 0x0328(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CRDPlayerTrackerWidget")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CRDPlayerTrackerWidget")
	}
	static class UCRDPlayerTrackerWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCRDPlayerTrackerWidget>();
	}
};
DUMPER7_ASSERTS_UCRDPlayerTrackerWidget;

}

