#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DoorSoundIndicatorComponent

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DoorSoundIndicatorComponent.DoorSoundIndicatorComponent_C
// 0x0000 (0x0158 - 0x0158)
class UDoorSoundIndicatorComponent_C final : public UFortSoundIndicatorComponent
{
public:
	TArray<EFortTeamAffiliation> GetAffiliationsToShowFor() const;
	bool ShouldShowSoundIndicator(class AFortPlayerController* PlayerController) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DoorSoundIndicatorComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DoorSoundIndicatorComponent_C")
	}
	static class UDoorSoundIndicatorComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDoorSoundIndicatorComponent_C>();
	}
};
DUMPER7_ASSERTS_UDoorSoundIndicatorComponent_C;

}

