#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DSA_BR_Ch5S1

#include "Basic.hpp"

#include "DSA_BR_Ch5_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DSA_BR_Ch5S1.DSA_BR_Ch5S1_C
// 0x0000 (0x0790 - 0x0790)
class ADSA_BR_Ch5S1_C final : public ADSA_BR_Ch5_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DSA_BR_Ch5S1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DSA_BR_Ch5S1_C")
	}
	static class ADSA_BR_Ch5S1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADSA_BR_Ch5S1_C>();
	}
};
DUMPER7_ASSERTS_ADSA_BR_Ch5S1_C;

}

