#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DualBladeMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass DualBladeMenu.DualBladeMenu_C
// 0x0018 (0x0478 - 0x0460)
class UDualBladeMenu_C final : public UFortDualBladeMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0460(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               MainOverlay;                                       // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_xp;                                        // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnInitialized();
	void OnFullScreenWidgetCreated(class UWidget* NewWidget);
	void ExecuteUbergraph_DualBladeMenu(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DualBladeMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DualBladeMenu_C")
	}
	static class UDualBladeMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDualBladeMenu_C>();
	}
};
DUMPER7_ASSERTS_UDualBladeMenu_C;

}

