#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EnvQueryContext_Milkshake_AllEarthquakes

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EnvQueryContext_Milkshake_AllEarthquakes.EnvQueryContext_Milkshake_AllEarthquakes_C
// 0x0000 (0x0030 - 0x0030)
class UEnvQueryContext_Milkshake_AllEarthquakes_C final : public UEnvQueryContext_BlueprintBase
{
public:
	void ProvideActorsSet(class UObject* QuerierObject, class AActor* QuerierActor, TArray<class AActor*>* ResultingActorsSet) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EnvQueryContext_Milkshake_AllEarthquakes_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EnvQueryContext_Milkshake_AllEarthquakes_C")
	}
	static class UEnvQueryContext_Milkshake_AllEarthquakes_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEnvQueryContext_Milkshake_AllEarthquakes_C>();
	}
};
DUMPER7_ASSERTS_UEnvQueryContext_Milkshake_AllEarthquakes_C;

}

