#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FirstPlaceHighlightActor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FirstPlaceHighlightActor.FirstPlaceHighlightActor_C
// 0x0018 (0x02C0 - 0x02A8)
class AFirstPlaceHighlightActor_C final : public AFortSpectatorPlayerHighlighter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               FirstPlacePlayerMaterialInstance;                  // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void SpectatorCameraTypeChanged(ESpectatorCameraType NewCameraType);
	void ReceiveBeginPlay();
	void PlayerTeamColorChanged(const struct FLinearColor& TeamColor);
	void FirstPlaceHighlightEnabledChanged(bool bInFirstPlaceHighlightEnabled);
	void ExecuteUbergraph_FirstPlaceHighlightActor(int32 EntryPoint);
	void BeingFollowedBySpectatorCamChanged(bool bInBeingFollowedBySpectatorCam);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FirstPlaceHighlightActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FirstPlaceHighlightActor_C")
	}
	static class AFirstPlaceHighlightActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFirstPlaceHighlightActor_C>();
	}
};
DUMPER7_ASSERTS_AFirstPlaceHighlightActor_C;

}

