#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Riding_Creature_EnergyDepleted_Grandma

#include "Basic.hpp"

#include "GA_Riding_Creature_EnergyDepleted_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Riding_Creature_EnergyDepleted_Grandma.GA_Riding_Creature_EnergyDepleted_Grandma_C
// 0x0000 (0x0EA8 - 0x0EA8)
class UGA_Riding_Creature_EnergyDepleted_Grandma_C final : public UGA_Riding_Creature_EnergyDepleted_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Riding_Creature_EnergyDepleted_Grandma_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Riding_Creature_EnergyDepleted_Grandma_C")
	}
	static class UGA_Riding_Creature_EnergyDepleted_Grandma_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Riding_Creature_EnergyDepleted_Grandma_C>();
	}
};
DUMPER7_ASSERTS_UGA_Riding_Creature_EnergyDepleted_Grandma_C;

}

