#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Athena_Ascender_DestroyBuilding

#include "Basic.hpp"

#include "GET_DirectPhysicalDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Athena_Ascender_DestroyBuilding.GE_Athena_Ascender_DestroyBuilding_C
// 0x0000 (0x0A68 - 0x0A68)
class UGE_Athena_Ascender_DestroyBuilding_C final : public UGET_DirectPhysicalDamage_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Athena_Ascender_DestroyBuilding_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Athena_Ascender_DestroyBuilding_C")
	}
	static class UGE_Athena_Ascender_DestroyBuilding_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Athena_Ascender_DestroyBuilding_C>();
	}
};
DUMPER7_ASSERTS_UGE_Athena_Ascender_DestroyBuilding_C;

}

