#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Helios_Rock_3dDecal_ChapCoastC

#include "Basic.hpp"

#include "Helios_Rock3dDecal_PARENT_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Helios_Rock_3dDecal_ChapCoastC.Helios_Rock_3dDecal_ChapCoastC_C
// 0x0000 (0x0360 - 0x0360)
class AHelios_Rock_3dDecal_ChapCoastC_C final : public AHelios_Rock3dDecal_PARENT_BP_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Helios_Rock_3dDecal_ChapCoastC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Helios_Rock_3dDecal_ChapCoastC_C")
	}
	static class AHelios_Rock_3dDecal_ChapCoastC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHelios_Rock_3dDecal_ChapCoastC_C>();
	}
};
DUMPER7_ASSERTS_AHelios_Rock_3dDecal_ChapCoastC_C;

}

