#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NavLink_Blockout_Floor_Curved_Small

#include "Basic.hpp"

#include "FortniteAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NavLink_Blockout_Floor_Curved_Small.NavLink_Blockout_Floor_Curved_Small_C
// 0x0000 (0x0080 - 0x0080)
class UNavLink_Blockout_Floor_Curved_Small_C final : public UFortNavLinkDefinition
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NavLink_Blockout_Floor_Curved_Small_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NavLink_Blockout_Floor_Curved_Small_C")
	}
	static class UNavLink_Blockout_Floor_Curved_Small_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNavLink_Blockout_Floor_Curved_Small_C>();
	}
};
DUMPER7_ASSERTS_UNavLink_Blockout_Floor_Curved_Small_C;

}

