#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PalletJack

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PalletJack.PalletJack_C
// 0x0000 (0x0BC8 - 0x0BC8)
class APalletJack_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PalletJack_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PalletJack_C")
	}
	static class APalletJack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APalletJack_C>();
	}
};
DUMPER7_ASSERTS_APalletJack_C;

}

