#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PCGBP_SplitPointDataByIndex

#include "Basic.hpp"

#include "PCG_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PCGBP_SplitPointDataByIndex.PCGBP_SplitPointDataByIndex_C
// 0x0010 (0x0078 - 0x0068)
class UPCGBP_SplitPointDataByIndex_C final : public UPCGBlueprintElement
{
public:
	int32                                         A_Threshold_Index;                                 // 0x0068(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         B_Threshold_Index;                                 // 0x006C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         C_Threshold_Index;                                 // 0x0070(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         D_Threshold_Index;                                 // 0x0074(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteWithContext(struct FPCGContext& InContext, const struct FPCGDataCollection& Input, struct FPCGDataCollection* Output);

	class FName NodeTitleOverride() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PCGBP_SplitPointDataByIndex_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PCGBP_SplitPointDataByIndex_C")
	}
	static class UPCGBP_SplitPointDataByIndex_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPCGBP_SplitPointDataByIndex_C>();
	}
};
DUMPER7_ASSERTS_UPCGBP_SplitPointDataByIndex_C;

}

