#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RCP_Palette_PortraitFrames

#include "Basic.hpp"

#include "RandomColor_Prop_Palette_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RCP_Palette_PortraitFrames.RCP_Palette_PortraitFrames_C
// 0x0000 (0x0040 - 0x0040)
class URCP_Palette_PortraitFrames_C final : public URandomColor_Prop_Palette_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RCP_Palette_PortraitFrames_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RCP_Palette_PortraitFrames_C")
	}
	static class URCP_Palette_PortraitFrames_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URCP_Palette_PortraitFrames_C>();
	}
};
DUMPER7_ASSERTS_URCP_Palette_PortraitFrames_C;

}

