#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SaveTheWorldRuntime

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class SaveTheWorldRuntime.FortSTWUIDataBase
// 0x0000 (0x0030 - 0x0030)
class UFortSTWUIDataBase : public UPrimaryDataAsset
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FortSTWUIDataBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FortSTWUIDataBase")
	}
	static class UFortSTWUIDataBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortSTWUIDataBase>();
	}
};
DUMPER7_ASSERTS_UFortSTWUIDataBase;

}

