#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarTagsEditorTagsHeader

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SidebarTagsEditorTagsHeader.SidebarTagsEditorTagsHeader_C
// 0x0000 (0x0508 - 0x0508)
class USidebarTagsEditorTagsHeader_C final : public USidebarTagsEditorHeaderWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SidebarTagsEditorTagsHeader_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SidebarTagsEditorTagsHeader_C")
	}
	static class USidebarTagsEditorTagsHeader_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USidebarTagsEditorTagsHeader_C>();
	}
};
DUMPER7_ASSERTS_USidebarTagsEditorTagsHeader_C;

}

