#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarSocialTagEditorTagList

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SidebarSocialTagEditorTagList.SidebarSocialTagEditorTagList_C
// 0x0000 (0x04B8 - 0x04B8)
class USidebarSocialTagEditorTagList_C final : public USidebarSocialTagListBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SidebarSocialTagEditorTagList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SidebarSocialTagEditorTagList_C")
	}
	static class USidebarSocialTagEditorTagList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USidebarSocialTagEditorTagList_C>();
	}
};
DUMPER7_ASSERTS_USidebarSocialTagEditorTagList_C;

}

