#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SparksCoreUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function SparksCoreUI.SparksQuestScreenContainer.HandleToggleQuestList
// 0x0001 (0x0001 - 0x0000)
struct SparksQuestScreenContainer_HandleToggleQuestList final
{
public:
	bool                                          bMapVisible;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SparksQuestScreenContainer_HandleToggleQuestList;

// Function SparksCoreUI.SparksQuestScreenContainer.SetQuestScreenVisible
// 0x0001 (0x0001 - 0x0000)
struct SparksQuestScreenContainer_SetQuestScreenVisible final
{
public:
	bool                                          bVisible;                                          // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SparksQuestScreenContainer_SetQuestScreenVisible;

// Function SparksCoreUI.SparksSongItemDetailsVM.OnSongCatalogRetrieved
// 0x0001 (0x0001 - 0x0000)
struct SparksSongItemDetailsVM_OnSongCatalogRetrieved final
{
public:
	bool                                          bSuccess;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SparksSongItemDetailsVM_OnSongCatalogRetrieved;

}

