#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Stage_Beam_light

#include "Basic.hpp"

#include "Stage_Beam_light_classes.hpp"
#include "Stage_Beam_light_parameters.hpp"


namespace SDK
{

// Function Stage_Beam_light.Stage_Beam_light_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void AStage_Beam_light_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stage_Beam_light_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stage_Beam_light.Stage_Beam_light_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void AStage_Beam_light_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stage_Beam_light_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stage_Beam_light.Stage_Beam_light_C.Size__UpdateFunc
// (BlueprintEvent)

void AStage_Beam_light_C::Size__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stage_Beam_light_C", "Size__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stage_Beam_light.Stage_Beam_light_C.Size__FinishedFunc
// (BlueprintEvent)

void AStage_Beam_light_C::Size__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stage_Beam_light_C", "Size__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stage_Beam_light.Stage_Beam_light_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AStage_Beam_light_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stage_Beam_light_C", "ReceiveTick");

	Params::Stage_Beam_light_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Stage_Beam_light.Stage_Beam_light_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AStage_Beam_light_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stage_Beam_light_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stage_Beam_light.Stage_Beam_light_C.ExecuteUbergraph_Stage_Beam_light
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AStage_Beam_light_C::ExecuteUbergraph_Stage_Beam_light(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stage_Beam_light_C", "ExecuteUbergraph_Stage_Beam_light");

	Params::Stage_Beam_light_C_ExecuteUbergraph_Stage_Beam_light Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Stage_Beam_light.Stage_Beam_light_C.Color__UpdateFunc
// (BlueprintEvent)

void AStage_Beam_light_C::Color__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stage_Beam_light_C", "Color__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stage_Beam_light.Stage_Beam_light_C.Color__FinishedFunc
// (BlueprintEvent)

void AStage_Beam_light_C::Color__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stage_Beam_light_C", "Color__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

