#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STW_MapPickupDisplayRuntime

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class STW_MapPickupDisplayRuntime.STW_PlayerControllerComponent_MapPickupDisplay
// 0x0000 (0x00A0 - 0x00A0)
class USTW_PlayerControllerComponent_MapPickupDisplay final : public UActorComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("STW_PlayerControllerComponent_MapPickupDisplay")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"STW_PlayerControllerComponent_MapPickupDisplay")
	}
	static class USTW_PlayerControllerComponent_MapPickupDisplay* GetDefaultObj()
	{
		return GetDefaultObjImpl<USTW_PlayerControllerComponent_MapPickupDisplay>();
	}
};
DUMPER7_ASSERTS_USTW_PlayerControllerComponent_MapPickupDisplay;

}

