#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tiered_Chest_Athena_Prepper

#include "Basic.hpp"

#include "Tiered_Chest_Athena_Parent_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tiered_Chest_Athena_Prepper.Tiered_Chest_Athena_Prepper_C
// 0x0010 (0x0F90 - 0x0F80)
class ATiered_Chest_Athena_Prepper_C final : public ATiered_Chest_Athena_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Tiered_Chest_Athena_Prepper_C;      // 0x0F80(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Custom_Chest_Aura;                                 // 0x0F88(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void HideChestOpenableCosmetics();
	void ExecuteUbergraph_Tiered_Chest_Athena_Prepper(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Tiered_Chest_Athena_Prepper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Tiered_Chest_Athena_Prepper_C")
	}
	static class ATiered_Chest_Athena_Prepper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATiered_Chest_Athena_Prepper_C>();
	}
};
DUMPER7_ASSERTS_ATiered_Chest_Athena_Prepper_C;

}

