#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Mobile_Augment_Selection_Proxy

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Mobile_Augment_Selection_Proxy.WBP_Mobile_Augment_Selection_Proxy_C
// 0x0008 (0x03D8 - 0x03D0)
class UWBP_Mobile_Augment_Selection_Proxy_C final : public UFortMobileHUDElementProxy
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_Mobile_Augment_Selection_Proxy(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Mobile_Augment_Selection_Proxy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Mobile_Augment_Selection_Proxy_C")
	}
	static class UWBP_Mobile_Augment_Selection_Proxy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Mobile_Augment_Selection_Proxy_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Mobile_Augment_Selection_Proxy_C;

}

