#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_Dialog

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UIKit_Dialog.WBP_UIKit_Dialog_C
// 0x0018 (0x0418 - 0x0400)
class UWBP_UIKit_Dialog_C final : public UCommonActivatableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0400(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUIKitDialogViewModel*                  UIKitDialogViewModel;                              // 0x0408(0x0008)(BlueprintVisible, ZeroConstructor, Transient, DuplicateTransient, RepSkip, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UWBP_UIKit_Dialog_Base_C*               Dialog_Base;                                       // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetUIKitDialogViewModel(class UUIKitDialogViewModel* ViewModel);
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_WBP_UIKit_Dialog(int32 EntryPoint);
	void BP_OnDeactivated();
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UIKit_Dialog_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UIKit_Dialog_C")
	}
	static class UWBP_UIKit_Dialog_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UIKit_Dialog_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UIKit_Dialog_C;

}

